### PR TITLE
Fix argument to match format specifier for ILP32 architectures.

### PR DESCRIPTION
**Pull request by xcllnt**

### CODE REVIEW

**Comment by xcllnt** [comment]
Sorry -- this has all the old stuff. I guess I need to create branches for every commit :-)

**Comment by philshafer** [comment]
On Aug 22, 2015, at 12:42 PM, xcllnt <notifications@github.com> wrote:
> Sorry -- this has all the old stuff. I guess I need to create branches for every commit :-)
> 

Ick.  I’m surprised the “Merge remote-tracking branch upstream/master” didn’t take care of this.  I’m assuming this is the result of a “git pull”.

Please confirm the delta is just:

--- a/libxo/libxo.c
+++ b/libxo/libxo.c
@@ -5373,7 +5373,8 @@ xo_dump_fields (xo_field_info_t *fields)

     for (xfip = fields; xfip->xfi_ftype; xfip++) {
 	printf("%lu(%u): %lx [%c/%u] [%.*s] [%.*s] [%.*s]\n",
-	       xfip - fields, xfip->xfi_fnum, (unsigned long) xfip->xfi_flags,
+	       (unsigned long) (xfip - fields), xfip->xfi_fnum,
+	       (unsigned long) xfip->xfi_flags,
 	       isprint((int) xfip->xfi_ftype) ? xfip->xfi_ftype : ' ',
 	       xfip->xfi_ftype,
 	       xfip->xfi_clen, xfip->xfi_content ?: “",

Thanks again for the patches!
 Phil

**Comment by xcllnt** [comment]
Confirmed. Just the cast.

-- 
Marcel (mobile)

**Comment by philshafer** [comment]
Fixed in 0.4.3

**Pull request closed without merging**
