### PR TITLE
Fix size_t/int issues in man pages.

### PR DESCRIPTION
**Pull request by trasz**

### CODE REVIEW

**Comment by philshafer** [comment]
Yes, this is an issue.  See https://github.com/Juniper/libxo/blob/master/libxo/xo.h#L129: <https://github.com/Juniper/libxo/blob/master/libxo/xo.h#L129:>

/*
 * Early versions of the API used "int" instead of "size_t" for buffer
 * sizes.  We want to fix this but allow for backwards compatibility
 * where needed.
 */
#ifdef USE_INT_RETURN_CODES
typedef int xo_ssize_t;         /* Buffer size */
#else /* USE_INT_RETURN_CODES */
typedef ssize_t xo_ssize_t;     /* Buffer size */
#endif /* USE_INT_RETURN_CODES */

This is similar in function, but designed to address backward compatibility.

Thanks,
 Phil

**Comment by trasz** [comment]
Yeah.  Still, do we need to mention that backward compatibility in the man pages?

**Comment by philshafer** [comment]
Yup, I need fix the man pages to use the new type.  I’ll try to finish it off this week.

Thanks,
 Phil

**Comment by trasz** [comment]
Does it mean I've missed some?

**Comment by philshafer** [comment]
Just checked in the xo_ssize_t under 638d6ba..324b055 and will spin a later tonight (after CI testing).

https://github.com/Juniper/libxo/commit/c11c8d207221d56e0edb1daf90e256954e1b32f2 <https://github.com/Juniper/libxo/commit/c11c8d207221d56e0edb1daf90e256954e1b32f2>

Please let me know what you think.

Thanks, 
 Phil

**Comment by philshafer** [comment]
fixed

**Pull request closed without merging**
